name: build
run-name: "Build and package"
on: [push]

jobs:
    build-bepinex:
        runs-on: ubuntu-latest
        container: mcr.microsoft.com/dotnet/sdk:6.0
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true
            - name: Publish
              run: >
                  dotnet run --project BepinEx/build/Build.csproj -- --target MakeDist

                  cp -r BepinEx/bin/dist/Unity.Mono-win-x64 ./dist
            - name: Upload
              uses: actions/upload-artifact@v4
              with:
                  path: dist/
                  if-no-files-found: error
